    <div class="wrapper-page">
        <div class="panel panel-color panel-inverse">
            <div class="panel-heading">
                <h3 class="text-center m-t-10"> Criar uma nova conta</h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal m-t-10 p-20 p-b-0" action="http://coderthemes.com/velonic_wb_3/admin_4/index.html">
                     <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" name="nome" type="text" id="name" required="" placeholder="Nome">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" name="email" type="email" id="email" required="" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control " name="username" type="text" id="username" required="" placeholder="Usuário">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control " name="password" type="password" required="" placeholder="Senha">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <label class="cr-styled">
                                <input type="checkbox" checked>
                                <i class="fa"></i>Eu aceito os <strong><a href="#">Termos e Condições</a></strong>
                            </label>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <div class="col-xs-12">
                            <button class="btn btn-success w-md" type="submit">Cadastrar</button>
                        </div>
                    </div>
                    <div class="form-group m-t-30">
                        <div class="col-sm-12 text-center">
                            <a href="login">Já tem conta?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
