    <div class="wrapper-page">
        <div class="panel panel-color panel-inverse">
            <div class="panel-heading">
                <h3 class="text-center m-t-10"> Recuperação de senha </h3>
            </div>
            <div class="panel-body">
                <form method="post" action="http://coderthemes.com/velonic_wb_3/admin_4/pages-login.html" role="form" class="text-center">
                    <div class="alert alert-info alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        Digite o seu e-mail e instruções serão enviadas para você!
                    </div>
                    <div class="form-group m-b-0">
                        <div class="input-group">
                            <input type="password" class="form-control" placeholder="Digite seu email">
                            <span class="input-group-btn"> <button type="submit" class="btn btn-success">Enviar</button> </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
