  </div>
        <!-- Page Content Ends -->
        <!-- ================== -->
        <!-- Footer Start -->
        <footer class="footer">
            2016 © Velonic.
        </footer>
        <!-- Footer Ends -->
    </section>
    <!-- Main Content Ends -->
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo JS; ?>jquery.js"></script>
    <script src="<?php echo JS; ?>bootstrap.min.js"></script>
    <script src="<?php echo JS; ?>modernizr.min.js"></script>
    <script src="<?php echo JS; ?>pace.min.js"></script>
    <script src="<?php echo JS; ?>wow.min.js"></script>
    <script src="<?php echo JS; ?>jquery.scrollTo.min.js"></script>
    <script src="<?php echo JS; ?>jquery.nicescroll.js" type="text/javascript"></script>
    <!-- Counter-up -->
    <script src="<?php echo JS; ?>waypoints.min.js" type="text/javascript"></script>
    <script src="<?php echo JS; ?>jquery.counterup.min.js" type="text/javascript"></script>
    <!-- sparkline -->
    <script src="<?php echo BOWER; ?>assets/sparkline-chart/jquery.sparkline.min.js" type="text/javascript"></script>
    <script src="<?php echo BOWER; ?>assets/sparkline-chart/chart-sparkline.js" type="text/javascript"></script>
    <!-- skycons -->
    <script src="<?php echo JS; ?>skycons.min.js" type="text/javascript"></script>
    <!--Morris Chart-->
    <script src="<?php echo BOWER; ?>assets/morris/morris.min.js"></script>
    <script src="<?php echo BOWER; ?>assets/morris/raphael.min.js"></script>
    <script src="<?php echo JS; ?>jquery.app.js"></script>
    <!-- Dashboard -->
    <script src="<?php echo JS; ?>jquery.dashboard.js"></script>
    <script type="text/javascript">
    jQuery(document).ready(function($) {
        /* Counter Up */
        $('.counter').counterUp({
            delay: 100,
            time: 1200
        });
    });
    /* BEGIN SVG WEATHER ICON */
    if (typeof Skycons !== 'undefined') {
        var icons = new Skycons({
                "color": "#fff"
            }, {
                "resizeClear": true
            }),
            list = [
                "clear-day", "clear-night", "partly-cloudy-day",
                "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
                "fog"
            ],
            i;

        for (i = list.length; i--;)
            icons.set(list[i], list[i]);
        icons.play();
    };
    </script>
</body>
<!-- Mirrored from coderthemes.com/velonic_wb_3/admin_4/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 11 Aug 2016 22:27:24 GMT -->

</html>
