    <div class="wrapper-page">
        <div class="panel panel-color panel-inverse">
            <div class="panel-heading">
                <h3 class="text-center m-t-10"> Faça seu <strong>Login</strong> </h3>
            </div>
            <div class="panel-body">
                <form class="form-horizontal m-t-10 p-20 p-b-0" action="http://coderthemes.com/velonic_wb_3/admin_4/index.html">
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" placeholder="Usuário">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" placeholder="Senha">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <label class="cr-styled">
                                <input type="checkbox" checked>
                                <i class="fa"></i> Lembre de mim
                            </label>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <div class="col-xs-12">
                            <button class="btn btn-success w-md" type="submit">Login</button>
                        </div>
                    </div>
                    <div class="form-group m-t-30">
                        <div class="col-sm-7">
                            <a href="recuperar"><i class="fa fa-lock m-r-5"></i> Esqueceu sua senha?</a>
                        </div>
                        <div class="col-sm-5 text-right">
                            <a href="cadastro">Crie sua Conta</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
