
        <!-- js placed at the end of the document so the pages load faster -->
        <script src="<?php echo JS; ?>jquery.js"></script>
        <script src="<?php echo JS; ?>bootstrap.min.js"></script>
        <script src="<?php echo JS; ?>pace.min.js"></script>
        <script src="<?php echo JS; ?>wow.min.js"></script>
        <script src="<?php echo JS; ?>jquery.nicescroll.js" type="text/javascript"></script>
        <!--common script for all pages-->
        <script src="<?php echo JS; ?>jquery.app.js"></script>

    </body>

</html>
